@affiliate_proj_HostAddress = http://localhost:5177
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6ImNGZ3pDZE0vTFpNNUJzQnciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3RpeHNjem1kb2lhYmF4dXphZWhpLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjZmY5ZWZkOC0wM2U2LTRkOGYtODZhYy02OTJjOTg2NmFiODQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUxMzkwNjgzLCJpYXQiOjE3NTEzODcwODMsImVtYWlsIjoidXNlcjFAZG9tYWluLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzUxMzg3MDgzfV0sInNlc3Npb25faWQiOiIxYWY5MDE2Ny04N2VjLTQ2NDctYmJiMS1hMWU2MjIwYzdhNWQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.0SsC0ivxfmzI6jKOSe6ay-sl8_5WZrF_XpLWlcjEEXE

GET {{affiliate_proj_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{affiliate_proj_HostAddress}}/users/
Accept: application/json

###

GET {{affiliate_proj_HostAddress}}/users/5d18508e-c792-4e0f-972b-82d41718d927
Accept: application/json

###

GET {{affiliate_proj_HostAddress}}/users/5d18508e-c792-4e0f-972b-82d41718d000
Accept: application/json

###

POST {{affiliate_proj_HostAddress}}/users
Content-Type: application/json

{ 
    "uuid": "1e30b95f-875d-4a4b-a886-4715386e651e",
    "username": "bobby123",
    "password": "mynameistherealslimshady"
}

###

PUT {{affiliate_proj_HostAddress}}/users/5233d2b1-d7a6-4113-8500-6a7cce80c258
Content-Type: application/json

{
  "uuid": "5233d2b1-d7a6-4113-8500-6a7cce80c258",
  "username": "Lenny",
  "password": "LennyWasHere:)"
}

###

DELETE {{affiliate_proj_HostAddress}}/Users/1e30b95f-875d-4a4b-a886-4715386e651e

###

POST {{affiliate_proj_HostAddress}}/api/affiliatelink/set-affiliate-link
Content-Type: application/json

{
  "CreatorId": "cff9efd8-03e6-4d8f-86ac-692c9866ab84",
  "StoreId": "0198be6e-cda3-739f-9f30-6f51578c97de",
  "Link": "https://1fa2e2f0da2b.ngrok-free.app/aff123",
  "RefParam": "aff123",
  "ProductLink": "affiliate-project-dev-test.myshopify.com/products/gift-card"
}