@affiliate_proj_HostAddress = http://localhost:5177

###
// Validated to fail as it uses UserId and not CreatorId
POST {{affiliate_proj_HostAddress}}/api/affiliatelink/set-affiliate-link
Content-Type: application/json

{
  "CreatorId": "cff9efd8-03e6-4d8f-86ac-692c9866ab84",
  "StoreId": "0198be6e-cda3-739f-9f30-6f51578c97de",
  "Link": "https://1fa2e2f0da2b.ngrok-free.app/aff123",
  "RefParam": "aff123",
  "ProductLink": "affiliate-project-dev-test.myshopify.com/products/gift-card"
}

###
// Validated to succeed and create entry in DB
POST {{affiliate_proj_HostAddress}}/api/affiliatelink/set-affiliate-link
Content-Type: application/json

{
  "CreatorId": "b65b5723-4cad-4be0-990c-0f5f6eaac233",
  "StoreId": "0198be6e-cda3-739f-9f30-6f51578c97de",
  "Link": "https://1fa2e2f0da2b.ngrok-free.app/aff123",
  "RefParam": "aff123",
  "ProductLink": "affiliate-project-dev-test.myshopify.com/products/gift-card"
}

###
// Validated to retrieve by CreatorId
GET {{affiliate_proj_HostAddress}}/api/affiliatelink/get-affiliate-links
Content-Type: application/json

{
  "CreatorId": "b65b5723-4cad-4be0-990c-0f5f6eaac233",
  "Link": "",
  "RefParam": "",
  "ProductLink": ""
}

###
// Validated to retrieve by StoreId
GET {{affiliate_proj_HostAddress}}/api/affiliatelink/get-affiliate-links
Content-Type: application/json

{
  "StoreId": "0198be6e-cda3-739f-9f30-6f51578c97de",
  "Link": "",
  "RefParam": "",
  "ProductLink": ""
}

###
// Validated to fail to retrieve with no parameters
GET {{affiliate_proj_HostAddress}}/api/affiliatelink/get-affiliate-links
Content-Type: application/json

{
  "Link": "",
  "RefParam": "",
  "ProductLink": ""
}

###
// Validated to fail to retrieve with StoreId and CreatorId
GET {{affiliate_proj_HostAddress}}/api/affiliatelink/get-affiliate-links
Content-Type: application/json

{
  "CreatorId": "b65b5723-4cad-4be0-990c-0f5f6eaac233",
  "StoreId": "0198be6e-cda3-739f-9f30-6f51578c97de",
  "Link": "",
  "RefParam": "",
  "ProductLink": ""
}